CREATE TABLE [dbo].[SecurityGroup] (
	[Id] INT IDENTITY(1,1) NOT NULL,
    [Name] NVARCHAR(50) NOT NULL,
	[DisplayName] NVARCHAR(50) NULL
	CONSTRAINT [PK_SecurityGroup] PRIMARY KEY CLUSTERED ([Id] ASC)
)
