//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Api {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///    A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        internal Resource() {
        }
        
        /// <summary>
        ///    Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Api.Resource", typeof(Resource).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///    Overrides the current thread's CurrentUICulture property for all
        ///    resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to  AccountCode,AccountName,ParentAccountCode,AccountClass,ContraAccount,Cash,Company,Sign
        ///10000,Assets,,1,FALSE,FALSE,100,DR
        ///10100,Current Assets,10000,1,FALSE,FALSE,100,DR
        ///10110,Cash in Hand and in Bank,10100,1,FALSE,TRUE,100,DR
        ///10111,Regular Checking Account,10110,1,FALSE,FALSE,100,DR
        ///10112,Savings Account,10110,1,FALSE,FALSE,100,DR
        ///10113,Cash in Hand A/C,10110,1,FALSE,FALSE,100,DR
        ///10120,Accounts Receivable,10100,1,FALSE,FALSE,100,DR
        ///10130,Other Receivables,10100,1,FALSE,FALSE,100,DR
        ///10121,Allowance [rest of string was truncated]&quot;;.
        /// </summary>
        public static string coa {
            get {
                return ResourceManager.GetString("coa", resourceCulture);
            }
        }
    }
}
