name: Docker Image CI

on:
  push:
    branches: [ "vscode-devcontainer" ]
  pull_request:
    branches: [ "vscode-devcontainer" ]
  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker-compose build
